
# render.yaml

# Definiuje, że jest to plik manifestu Render


# Lista usług do wdrożenia
services:
  # Tutaj znajdują się definicje poszczególnych usług
  - type: web
    # ... inne parametry usługi webowej ...

    # ... inne parametry bazy danych ...
